# Generated by Django 4.2.4 on 2023-08-02 06:35

from django.db import migrations
import santri.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='foto',
            field=santri.compress_image.CompressedImageField(blank=True, default='no-image.png', help_text='format logo .jpg/.jpeg', null=True, quality=50, upload_to='kelas'),
        ),
    ]
