# Generated by Django 4.2.4 on 2023-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0002_santri_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hafalansantri',
            name='catatan',
            field=models.CharField(default='', max_length=200),
        ),
    ]
