# Generated by Django 4.2.4 on 2023-08-02 05:56

from django.db import migrations, models
import santri.compress_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilWalikelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(max_length=100)),
                ('niy', models.CharField(blank=True, max_length=100, null=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pendidikan', models.CharField(max_length=150)),
                ('foto', santri.compress_image.CompressedImageField(blank=True, default='no-image.png', help_text='format logo .jpg/.jpeg', null=True, quality=50, upload_to='ustadz')),
            ],
        ),
    ]
